### ISSUE TITLE
fail to Write GFA file

### ISSUE THREAD

**Issue by lonestarling** [xfengnefx/hifiasm-meta#5]
Hi xfengenfx

recently，i use the hifiam-meta  to assemble my metagenomic HIFI data，i encountered same error in two times  at two compute
cluster，which shows stop at the Writing GFA step suddenly. here is my two  log file, the first one was in the slurm system,the second one was in the usual system.    so  i can't get my final contig GFA file ,can you figure it out for me. 
[job-26237_1.err.txt](https://github.com/xfengnefx/hifiasm-meta/files/7099826/job-26237_1.err.txt)
[nohup.out.txt](https://github.com/xfengnefx/hifiasm-meta/files/7099828/nohup.out.txt)
appreciate it

**Comment by xfengnefx** [comment]
Looks like I have a bug. Is there anything in the r_utg gfa file? Could you compile hifiasm-meta with ASan and rerun from bin files (will skip ovec and the initial graph building stage)? Which is to:

```
cd $DIR  # hifiasm-meta's source code folder
export asan=1
make -B
cd $WORK_DIR  # the assembly folder
hifiasm_meta --dbg-gfa -V -o BMXV01 -t32 $INPUT/BMXV01_CCS_subreads.fastq.gz 2>log_asan
```
Please include the compile steps in the job script (instead of manually `make` then submit a slurm job). If ASan is not available or hits memory limit, rerun with `hifiasm_meta --dbg-gfa -V -o BMXV01 -t32 $INPUT/BMXV01_CCS_subreads.fastq.gz 2>log_asan` alone is also helpful (`-V` gives more logging before the segfault point).

**Comment by lonestarling** [comment]
Hi
thank you for your prompt reply， actually，in three days ago，before i ask for help here，i use hifi-meta to assemble two samples by the same script，one is successful ，another is unsuccessfull with the core dump error。
i try to set the “export asn=1，make-B”   it seems that something error with it，like /usr/bin/ld/can't find/usr/lib64/libasno.so.0.0.0

i check the r_utg GFA file was generated ,and it seems complete,and the result also include the p_utg gfa p_utg.noseq.gfa r_utg.noseq.gfa , except the a_ctg gfa.

so i will try the set"-- dbg-gfa -V"this time according your advice.
thank you so much.

**Comment by xfengnefx** [comment]
Was that a typo in `export asn=1`? If it was actually correct (`export asan=1`) but linker failed, then nevermind. 

I haven't seen this segfault in my test datasets, perhaps there's a complex local topology and hit the buggy part in contig graph cleaning. I should look to compile some unit tests in the future.

**Comment by xfengnefx** [comment]
@lonestarling I've pushed r53 to the `meta` branch, which probably fixed this segfault you saw.

To use previous bin files: if you're working in the same directory as before, use the prefix in previous runs for `-o $run_prefix`; otherwise `-B $old_prefix -o $new_prefix` should do. If you used `--dbg-gfa` before, set that too to save time.
